plugin 'exception_notifier', :git => 'git://github.com/rails/exception_notification.git'
plugin 'authlogic', :git => 'git://github.com/binarylogic/authlogic.git'
plugin 'paperclip', :git => 'git://github.com/thoughtbot/paperclip.git'
plugin 'asset_packager', :git => 'http://synthesis.sbecker.net/pages/asset_packager'
plugin 'lazy_developer', :git => 'git://github.com/napcs/lazy_developer.git'
plugin 'annotate_models', :svn => 'http://repo.pragprog.com/svn/Public/plugins/annotate_models'